---
title: "Group Data Documentation (wbpip)"
author: "Diana Garcia"
format: 
  html:
    number-sections: true
    mermaid:
      theme: sandstone
---

> ## Objective {.unnumbered}
>
> This document aims to describe the functions used in `wbpip` to calculated the poverty and inequality statistics using group data.

<!-- I start by presenting the structure of the functions and then there is a description on how each function is built. -->

## Structure {.unnumbered}

```{mermaid}
flowchart TD
    lz(select_lorenz) --> stats[pip_stats]
    lq(pip_stats_lq) --> lz
    lb(pip_stats_lb) --> lz  
    form_lq(functional_form_lq) --> lq
    derive_lq(derive_lq) --> lq
    est_lq(estimate_lq) --> lq
    check_val(check_curve_validity_lq) --> est_lq
    comp_dist_lq(compute_dist_stats_lq) --> est_lq
    polarization_lq(polarization_lq) --> comp_dist_lq
    gini_lq(gini_lq) --> comp_dist_lq
    value_at_lq --> polarization_lq
    value_at_lq(value_at_lq) --> comp_dist_lq
    mld_lq(mld_lq) --> comp_dist_lq
    quantile_lq(quantile_lq) --> comp_dist_lq
    derive_lq --> comp_dist_lq
    derive_lq --> mld_lq
    derive_lq --> polarization_lq
    value_at_lq --> quantile_lq

```


## Functions

### pip_stats {#sec-pip_stats}

*Description*: Compute poverty statistics for grouped data by selecting the best functional fit for the Lorenz curve (either beta or quadratic)

::: {#nte-boundary-issue .callout-note}
#### Issue: Boundary conditions 

At the moment, this is calculated using $(\mu L'(0.001) + 4,\mu L'(0.98) - 4)$ (*Note: Not sure what is the reason of adding and subtracting 4*). 

:::

### select_lorenz {#sec-select_lorenz}

*Description*: Select best Lorenz fit and adjust the returned statistics if needed.

### pip_stats_lq

*Description*: Compute poverty statistics for grouped data using the quadratic functional form of the Lorenz qurve.

### pip_stats_lb

*Description*: Compute poverty statistics for grouped data using the beta functional form of the Lorenz qurve.

### functional_form_lq

*Description*: Prepares data for regression of $y(1-y)$ on $(x^2-y)$, $y(x-1)$ and $(x-y)$. 

*Note*: The last observation of (x,y), which by construction has the value (1, 1), is excluded since the functional form for the Lorenz curve already forces it to pass through the point (1, 1). 

*References*: [1]

*Relevant equations*:

The general Quadratic Lorenz curve form is: 

$$ax^2 + bxy + cy^2 + dx + ey + f = 0$$ {#eq-gen-equation}

where $y$ is the vector of cumulative proportion of consumption/income (L) and $x$ is the cumulative proportions of population (P). Using the condition $e = -(a+b+d+1)$ the previous equation is rewritten in a linear form as follows (Equation 15 in Villasenor et al, 1989):

$$y(1-y) = a(x^2-y) + by(x-1) + d(x-y)$$ {#eq-linear-form}

This function prepares data to estimate $a$, $b$, and $d$ (*Note*: $d$ is named $C$ in `wbpip`).


### value_at_lq: 

*Description*: Solves for the Quadratic Lorenz curves.

*References*: [1]

*Relevant equations*:

This function calculates the value at the Quadratic Lorenz Curve. Solving @eq-gen-equation for $y$, and assuming $f=0$ and $e = -(a+b+d+1)$ the density function that better fits income distributions will be (Equation 6b in Villasenor et al, 1989):

$$ y= \Bigl\{-(bx+e) - (\alpha x^2 + \beta x + e^2)^\frac{1}{2}\Bigl\}/2$$ {#eq-solve-y}

where $\alpha = b^2 -4a$ and $\beta = 2be - 4d$.

### derive_lq 

*Description*: returns the first derivative of the quadratic Lorenz curves with $c = 1$. 

*References*: [1]

*Relevant equations*:

This function computes the first derivative of @eq-solve-y:

$$-(b / 2) - (\beta + 2 \alpha x) / (4\sqrt(\alpha x^2 + \beta x + e^2)$$ {#eq-first-der}

### estimate_lq

*Description*: Estimates poverty and inequality stats from Quadratic Lorenz fit

### check_curve_validity_lq

*Description*: Check validity of Lorenz Quadratic fit

*References*: [1], [2], [3]

*Relevant equations*:

The function tests for specific assumptions for the Lorenz Quadratic and relies on the formulas from Table 2 in Datt, G (1998) [3]. The nomenclature for some of these formulas differ from Villasenor et al (1989), so this is how they match:

$m = \alpha = b^2 -4a$

$n = \beta = 2be -4c$ ($c=d$ for Villasenor et al, 1989)

$r = K*2\alpha = (n^2 - 4me^2)^\frac{1}{2}$ 

::: {#nte-cond-r-issue .callout-note}
#### Issue: Rename $r$ 

At the moment, $r$ refers to $(n^2 - 4me^2)$ in `wbpip`. This is already fixed on commit `47852c` in branch `fix_key_values` by Zander (Waiting for merge). We should maybe rename this within this function. 

:::

The conditions this function tests are presented in Section 4 of Datt (1998):

Normality and Validity

 - $(n^2 - 4me^2)>0$ so the square root in $r$ to be positive. (Normality and validity)
 - $e<0$ or $c>0$ so $L(0,y) = 0$ and $L'(0^{+},y) \geq 0$ (Normality and validity)
 - $a+d \geq 0.9$ so $L(1,y) = 1$ (Validity) 

::: {#imp-condad .callout-important}
#### Issue: The inequality for $a+d$

At the moment, we still use the old validation $a+d \leq 1$. However, the Corrigendum of the original paper [2] indicates we should use $a+d \geq 1$
:::

And so $L''(x,y) \geq 0$ for $x$ within $(0,1)$:

 - $m < 0$ (condition on Villasenor et al., 1989)
 - if $m > 0$ then $m < n^2/4 e^2$ and $n \leq 0$ (last condition from Datt,1998)
 - if $m > 0$ then $m < n^2/4 e^2$ and $m < -n/2$ (last condition from Datt,1998)
 
$L''(x,y)$ can be calculated using @eq-first-der:

$$ \frac{\beta^2 -4\alpha e^2}{8(\alpha x^2 + \beta x + e^2)^\frac{3}{2}} = \frac{n^2 - 4me^2}{8(mx^2 +nx +e^2)^\frac{3}{2}}=\frac{r^2}{8(mx^2 +nx +e^2)^\frac{3}{2}} $$

### compute_dist_stats_lq

*Description*: Computes distributional stats from Lorenz Quadratic fit

::: {#nte-check1 .callout-note}
#### Check: 

What is the difference with `gd_estimate_dist_stats_lq`?

:::

### quantile_lq

*Description*: Compute quantiles from Lorenz Quandratic fit

*Note*: This function calculates the quantiles for a Lorenz Quadratic with specific values for $a$, $b$ and $d$.  

::: {#imp-quant-gd-issue .callout-important}
#### Issues:  

The description of this function indicates that it calculates the quantiles (deciles) for the density for some specific values of $a$, $b$ and $d$, but it calculates instead the "share" or the value between the deciles (*Note: Not sure how this values is used later on in the pipeline*). 

Regarding the last decile, they manually calculated it by subtracting 1 to the second-to-last decile:

`vec[n_quantile] <- 1 - value_at_lq(x[n_quantile-1], A, B, C)` where `n_quantile = 10`

However, my hypothesis is that this is related to *Issue: The inequality for $a+d$* above. If $A+C \geq 1$ then `value_at_lq(1, A, B, C) = 1`

:::

### mld_lq

*Description*: Computes MLD from Lorenz Quadratic fit

*References*: ...

*Relevant equations*: ...

### gini_lq

*Description*: Compute Gini index from Lorenz Quadratic fit.

*References*: [3]

*Relevant equations*: ...

### polarization_lq

*Description*: Computes polarization index from parametric Lorenz fit

*References*: ...

*Relevant equations*: ...


## References:

1. Villasenor, J., B. C. Arnold. 1989. "[Elliptical Lorenz curves](https://doi.org/10.1016/0304-4076(89)90089-4)". *Journal of Econometrics 40* (2): 327-338.

2. Krause, M. 2013. "[Corrigendum to Elliptical Lorenz curves](https://doi.org/10.1016/j.jeconom.2013.01.001)". *Journal of Econometrics 174* (1): 44.

3. Datt, G. 1998. "[Computational Tools For Poverty Measurement And Analysis](https://www.ifpri.org/cdmref/p15738coll2/id/125673)". FCND Discussion Paper 50. World Bank, Washington, DC.

## Appendix: 

Find function using the following list of functions:

-  @sec-pip_stats: `gd_compute_pip_stats`
-  @sec-select_lorenz: `gd_select_lorenz`
- `gd_compute_pip_stats_lq`
- `gd_compute_pip_stats_lb`
- `create_functional_form_lq`
- `derive_lq`
- `gd_estimate_lq` 
- `check_curve_validity_lq`
- `gd_compute_dist_stats_lq`






